name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: shellcheck
      run: shellcheck tests/checkdocs.sh
    - name: check docs
      run: |
        cd tests
        ./checkdocs.sh
